{% set name = "pycountry" %}
{% set version = "26.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b6027d453fcd6060112b951dd010f01f168b51b4bf8a1f1fc8c95c8d94a0801

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.6,<4.0
    - setuptools

test:
  imports:
    - pycountry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pycountry/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: pycountry provides the ISO databases for the standards
  description: |
    The package includes a copy from Debian’s pkg-isocodes and makes the 
    data accessible through a Python API.
    Translation files for the various strings are included as well.
  doc_url: https://pypi.org/project/pycountry/
  dev_url: https://github.com/flyingcircusio/pycountry

extra:
  recipe-maintainers:
    - CurtLH
