schema_version: 1

context:
  version: "26.2.16"

package:
  name: pycountry
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pycountry/pycountry-${{ version }}.tar.gz
  sha256: 5b6027d453fcd6060112b951dd010f01f168b51b4bf8a1f1fc8c95c8d94a0801

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - setuptools

tests:
  - python:
      imports:
        - pycountry
      python_version:
        - ${{ python_min }}.*
        - '*'
      pip_check: true

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  summary: pycountry provides the ISO databases for the standards
  description: |
    The package includes a copy from Debian’s pkg-isocodes and makes the
    data accessible through a Python API.
    Translation files for the various strings are included as well.
  homepage: https://pypi.org/project/pycountry/
  repository: https://github.com/flyingcircusio/pycountry
  documentation: https://pypi.org/project/pycountry/

extra:
  recipe-maintainers:
    - CurtLH
    - xhochy
